name: OWASP ZAP Scan

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Scan target with ZAP baseline scan
        run: |
          docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py \
            -t https://juice-shop.herokuapp.com/#/ \
            -r zap_report.html

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-html-report
          path: zap_report.html
