name: OWASP ZAP Scan

on: [push]

jobs:
  zap-scan:
    name: Run ZAP Baseline Scan
    runs-on: ubuntu-latest

    steps:
      - name: OWASP ZAP Baseline Scan
        uses: actions/checkout@v3

      - name: Install OWASP ZAP
        run: |
          sudo apt-get update
          sudo apt-get install -y zaproxy
          pip install zap-cli

      # 3. Definir la URL del objetivo (la URL de tu aplicación)
      - name: Set target URL
        run: |
          echo "TARGET_URL=https://juice-shop.herokuapp.com/#/" >> $GITHUB_ENV  # Cambia esta URL al objetivo real

      # 4. Escanear con OWASP ZAP
      - name: Run OWASP ZAP scan
        run: |
          zap-cli quick-scan --url $TARGET_URL

      # 5. Subir los resultados del escaneo
      - name: Upload ZAP Report as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
