name: OWASP ZAP Scan

on: [push]

jobs:
  zap-scan:
    name: Run ZAP Baseline Scan
    runs-on: ubuntu-latest

    steps:
      - name: OWASP ZAP Baseline Scan
        uses: actions/checkout@v3

      - name: Run ZAP scan against target
        run: |
          docker run -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zap-baseline:latest \
            -t "https://juice-shop.herokuapp.com/#/" \
            -g gen.conf \
            -r zap-report.html || true

      - name: Subir reporte como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: zap-html-report
          path: zap-report.html
