name: OWASP ZAP Scan

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Run OWASP ZAP Full Scan
        run: |
          docker run --rm -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py \
            -t https://juice-shop.herokuapp.com \
            -r full_zap_report.html \
            -x full_zap_report.xml \
            -I

      - name: Upload ZAP HTML report
        uses: actions/upload-artifact@v4
        with:
          name: Full ZAP HTML Report
          path: full_zap_report.html

      - name: Upload ZAP XML report
        uses: actions/upload-artifact@v4
        with:
          name: Full ZAP XML Report
          path: full_zap_report.xml
