name: OWASP ZAP Scan

on: [push]

jobs:
  zap-scan:
    name: Run ZAP Baseline Scan
    runs-on: ubuntu-latest

    steps:
      - name: OWASP ZAP Baseline Scan
        uses: actions/checkout@v3

     # 2. Instalar OWASP ZAP usando el script oficial
      - name: Install OWASP ZAP
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.15.0/ZAP_2.15.0_Linux.tar.gz
          tar -xvzf ZAP_2.13.0_Linux.tar.gz
          sudo mv ZAP_2.13.0 /opt/zaproxy
          sudo ln -s /opt/zaproxy/zap.sh /usr/local/bin/zap

      # 3. Definir la URL del objetivo
      - name: Set target URL
        run: |
          echo "TARGET_URL=https://juice-shop.herokuapp.com/#/" >> $GITHUB_ENV  # Cambia esta URL al objetivo real

      # 4. Escanear con OWASP ZAP
      - name: Run OWASP ZAP scan
        run: |
          zap-cli quick-scan --url $TARGET_URL

      # 5. Subir los resultados del escaneo
      - name: Upload ZAP Report as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
